# Create a Docker compose file to start up all the 
# previous containers. This Docker Compose file will 
# start the following systems:

# - TortoiseBot Gazebo simulation
# - Mapping nodes
# - RViz2 to visualize the mapping process

version: '3.7'
services:
    gazebo_server:
        hostname: gazebo_server
        # build:
        #     context: .
        #     dockerfile: tortoisebot-ros2-gazebo
        image: andyleo10/andres.alamo-cp22:tortoisebot-ros2-gazebo
        container_name: gazebo_server
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - ros-net2
        command: /bin/bash -c "sleep 2 && source /opt/ros/galactic/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=True"

    waypoints_server:
        hostname: waypoints_server
        build:
            context: .
            dockerfile: tortoisebot-ros2-waypoints
        #image: andyleo10/andres.alamo-cp22:tortoisebot-ros2-slam
        container_name: waypoints_container
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - ros-net2
        command: /bin/bash -c "sleep 12 && source /opt/ros/galactic/setup.bash && source /ros2_ws/install/setup.bash && ros2 run tortoisebot_waypoints tortoisebot_action_server"

    waypoints_client:
        hostname: waypoints_client
        build:
            context: .
            dockerfile: tortoisebot-ros2-waypoints
        #image: andyleo10/andres.alamo-cp22:tortoisebot-ros2-slam
        container_name: test_cpp_container
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - ros-net2
        command: /bin/bash -c "sleep 14 && source /opt/ros/galactic/setup.bash && source /ros2_ws/install/setup.bash && colcon test --packages-select tortoisebot_waypoints --event-handler=console_direct+"

networks:
    ros-net2:    
